services:
  mysql:
    image : mysql
    environment:
      MYSQL_DATABASE : signizi
      MYSQL_USER : user
      MYSQL_PASSWORD : user
      MYSQL_ROOT_PASSWORD : root
      MYSQL_ALLOW_EMPTY_PASSWORD : "yes"
    ports :
      - 3306:3306
    networks:
      - springboot-mysql-net
    healthcheck:
      test: ['CMD-SHELL','mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 2s
      retries: 100

  server:
    build:
      context: lifeguard_server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge
